### ISSUE TITLE
Include guidelines for composition?

### ISSUE THREAD

**Issue by peteruithoven** [TraumaD/elementary-icon-templates#1]
The HIG mentions preferred measurements for composition of icons:
https://elementary.io/docs/human-interface-guidelines#composition
Maybe those could be included as guidelines? 

Maybe this doesn't make sense for templates where there is already a base shape, but since they recommend creating icons with a "distinctive shape/silhouette" it might be useful to create an "empty template" This could just define the size, grid and guidelines.

**Comment by micahilbery** [comment]
I'm not really sure how to go about this. The problem with offering blank templates with the guides is that there isn't really a set x or mean height for every icon you could make. It really depends of the shape and the visual weight of the icon. (the reason that circular icons extend past squared ones) This is a big reason I say several times that these templates don't replace the HIG. If I remember correctly I include grids in the files. I guess I could include some guides for the base, mean, and x heights for them although idk how helpful they would be except maybe the mean height guide.

**Comment by peteruithoven** [comment]
I'd mostly say they would literally be guidelines, they would make it easier to visualize them than the table included in the HIG.

**Comment by micahilbery** [comment]
I've tried doing this a few different ways and it always just comes out as a bunch of guide lines that without context are just confusing and don't feel very useful. I'm going to close this out as a design conflict but If someone else can make this feel right and make it useful I'm open to PRs.
