### ISSUE TITLE
Potential issue with appstream rendering of the vertical rectangle icon.

### ISSUE THREAD

**Issue by micahilbery** [TraumaD/elementary-icon-templates#7]
![image](https://user-images.githubusercontent.com/10608836/76015416-ccce9f80-5ee0-11ea-9465-fe94308501e5.png)
![image (1)](https://user-images.githubusercontent.com/10608836/76015422-cdffcc80-5ee0-11ea-88ca-1c878bf0ab5c.png)
I think both of these icons were made using this template

**Comment by SubhadeepJasu** [comment]
Can confirm that Pebbles icon was indeed based on this template.
